### ISSUE TITLE
Blurry sidebar buttons

### ISSUE THREAD

**Issue by FivelFox** [folt-a/godot-idea-board#16]
Not sure if I did something wrong or if it's a bug. I noticed it wasn't blurry in the screenshot in the readme so I thought I would report. I'm on Godot 4.0.2

![image](https://github.com/folt-a/godot-idea-board/assets/118695973/a0d37602-88fa-4ac6-83d4-807425c0dc7c)

**Comment by folt-a** [comment]
Thank you for your report.
What is your OS and display resolution?

**Comment by FivelFox** [comment]
Fedora Linux, 1366x768 (16:9)

**Comment by folt-a** [comment]
fixed it.
Can you confirm that it is fixed in your environment?
![image](https://github.com/folt-a/godot-idea-board/assets/32963227/7cee0c98-5c9d-44a9-b03c-0fb99644f71a)

**Comment by FivelFox** [comment]
Fresh install on a new project, unfortunately not fixed :(
![image](https://github.com/folt-a/godot-idea-board/assets/118695973/851ed55b-d59d-43ff-8061-12adfb5fad04)

**Comment by folt-a** [comment]
oh,
Did you download this addon from github?
it did not fixed in Assetlib yet.

**Comment by FivelFox** [comment]
Oh! That... makes sense lol. It seems like it might be fixed!
![image](https://github.com/folt-a/godot-idea-board/assets/118695973/e3d3fda2-5df1-4a48-8362-e908f5df4315)
